[project]
name = "wishlist-service-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.11",
    "motor>=3.7.0",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.1",
    "uvicorn>=0.34.0",
]
